#!/usr/bin/env python3
"""
AAC Factory compiled-agent runtime. Generated by compile_agent.py — edit handlers/, not this.

v0.3 runtime truth: executable gates are compiled, model identity is recorded as
requested vs actual, unknown usage stays unknown, and finite batch work emits a
parent run summary plus child run cards.
"""

from __future__ import annotations

import json
import re
import sys
import time
import uuid
from pathlib import Path
from typing import Any

BUILD = Path(__file__).resolve().parent
PKG = BUILD.parent.parent  # build/agent -> package root
sys.path.insert(0, str(BUILD))

import gate_grammar  # noqa: E402
import llm_adapters  # noqa: E402
import runcard  # noqa: E402

GRAPH = json.loads((BUILD / "nodes.json").read_text(encoding="utf-8"))
SINKS = {"happy_sink", "refuse_sink", "hard_refuse_sink"}
LEAK_PATTERNS = [re.compile(p) for p in (
    r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-z]{2,}",
    r"\b\(?\d{3}\)?[-.\s]\d{3}[-.\s]\d{4}\b",
    r"\b\d{3}-\d{2}-\d{4}\b",
)]


def now() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def kill_switch_active() -> bool:
    return (BUILD.parent / "KILL").exists()


def hard_refuse_hit(text: str, classes: list[str]) -> str | None:
    for pat in LEAK_PATTERNS:
        if pat.search(text):
            return "leak_pattern_detected"
    low = text.lower()
    for c in classes:
        token = c.split(":")[0].strip().lower()[:40]
        if token.startswith("phi") and "patient" in low:
            return c
    return None


def _parse_jsonish(raw: str) -> dict[str, Any]:
    return json.loads(raw[raw.find("{"): raw.rfind("}") + 1])


def execute_output_gates(node: dict, out: dict, gates: dict) -> list[str]:
    failures: list[str] = []
    for gate in node.get("output_gates") or []:
        rule = gate.get("rule", "")
        ok, reason = gate_grammar.execute_gate(rule, out, context={"confidence_floor": node.get("confidence_floor", 0.6)})
        if not ok:
            failures.append(f"{gate.get('gate_id', 'gate')}: {reason}")
    if failures:
        gates["output"] = "fail (" + "; ".join(failures) + ")"
    return failures


def execute_node(node: dict, ctx: dict, report: list[str]) -> tuple[dict, dict, dict | None]:
    """Returns (output, gate_outcomes, adapter_result)."""
    gates = {"input": "pass", "output": "not_run", "cross_check": "not_run", "action": "pass (no effectors exist)"}
    rm = node["runtime_mode"]

    if rm == "H":
        qdir = PKG / "process" / "run-cards" / "_review_queue"
        qdir.mkdir(parents=True, exist_ok=True)
        item = {"node_id": node["node_id"], "ctx_ref": ctx.get("_ref", ""), "queued_at": now(),
                "payload_excerpt": json.dumps(ctx, default=str)[:1500]}
        (qdir / f"{node['node_id']}__{ctx['_run_id']}.json").write_text(
            json.dumps(item, indent=2) + "\n", encoding="utf-8")
        gates["output"] = "pass (queued for human)"
        return {"decision": "queued_for_human", "confidence": 1.0}, gates, None

    if rm == "D":
        try:
            handler = __import__(f"handlers.{node['module']}", fromlist=["run"])
            out = handler.run(dict(ctx))
            if out.get("_unimplemented"):
                gates["input"] = gates["output"] = "skipped_unimplemented_handler"
                report.append(f"{node['node_id']}: handler unimplemented — pass-through (shadow only)")
                return {**ctx, "_unimplemented": True, "decision": "pass_through", "confidence": 1.0}, gates, None
            failures = execute_output_gates(node, out, gates)
            if failures:
                return {"decision": "refuse", "confidence": float(out.get("confidence") or 0),
                        "reason": "output_gate_failed: " + "; ".join(failures),
                        "_gate_failed": True,
                        "_certification_blockers": ["output_gate_failed"]}, gates, None
            gates["output"] = "pass"
            return out, gates, None
        except Exception as e:
            gates["output"] = f"fail ({type(e).__name__})"
            return {"decision": "refuse", "confidence": 0.0, "reason": f"handler error: {e}"}, gates, None

    sys_prompt = (BUILD / "prompts" / f"{node['module']}.md").read_text(encoding="utf-8")
    user_payload = json.dumps({k: v for k, v in ctx.items() if not k.startswith("_")},
                              default=str)[: node.get("token_budget_chars", 24000)]
    adapter = llm_adapters.complete_result(node["execution"], node.get("model", ""), sys_prompt, user_payload)
    try:
        out = _parse_jsonish(adapter["text"])
    except Exception:
        gates["output"] = "fail (non-json output)"
        return {"decision": "refuse", "confidence": 0.0, "reason": "model output not parseable",
                "_certification_blockers": ["non_json_output"]}, gates, adapter

    blockers: list[str] = []
    if not adapter.get("model_verified"):
        blockers.append("model_identity_unverified")

    hr = hard_refuse_hit(json.dumps(out, default=str), node.get("hard_refuse", []))
    if hr:
        gates["output"] = f"hard_refuse ({hr})"
        return {"decision": "hard_refuse", "confidence": 1.0, "reason": hr,
                "_certification_blockers": blockers}, gates, adapter

    floor = node.get("confidence_floor", 0.6)
    conf = float(out.get("confidence") or 0)
    bounded = node.get("bounded_actions") or []
    if bounded and str(out.get("decision", "")) not in bounded:
        gates["output"] = "fail (decision outside bounded set)"
        return {"decision": "refuse", "confidence": conf, "reason": "unbounded decision",
                "_certification_blockers": blockers + ["unbounded_decision"]}, gates, adapter
    gate_failures = execute_output_gates(node, out, gates)
    if gate_failures:
        return {"decision": "refuse", "confidence": conf,
                "reason": "output_gate_failed: " + "; ".join(gate_failures),
                "_gate_failed": True,
                "_certification_blockers": blockers + ["output_gate_failed"]}, gates, adapter
    if conf < floor:
        gates["output"] = f"below_floor ({conf} < {floor}) -> human"
        out["_below_floor"] = True
    else:
        gates["output"] = "pass"
    if blockers:
        out["_certification_blockers"] = blockers
    return out, gates, adapter


def route(node: dict, out: dict) -> str:
    if out.get("decision") == "hard_refuse":
        return "hard_refuse_sink"
    if out.get("_gate_failed"):
        return "refuse_sink"
    if out.get("_below_floor"):
        return node.get("below_floor_route", "refuse_sink")
    for e in node.get("edges", []):
        if gate_grammar.eval_condition(e["condition"], out):
            return e["to"]
    return node.get("default_route", "refuse_sink")


def _adapter_card_fields(adapter: dict | None) -> dict:
    if not adapter:
        return {}
    usage = adapter.get("usage") or {}
    return {
        "requested_model": adapter.get("requested_model"),
        "actual_model": adapter.get("actual_model", "unknown"),
        "model_verified": bool(adapter.get("model_verified")),
        "verification_source": adapter.get("verification_source", "unverified"),
        "executor": adapter.get("executor", "unknown"),
        "adapter_version": adapter.get("adapter_version", "unknown"),
        "usage": {"tokens_in": usage.get("tokens_in", "unknown"),
                  "tokens_out": usage.get("tokens_out", "unknown"),
                  "cost_usd": "unknown",
                  "usage_source": usage.get("source", "unknown"),
                  "actual_usage_available": bool(usage.get("actual_usage_available", False))},
    }


def _as_ref_list(value) -> list[str]:
    if value is None:
        return []
    raw = value if isinstance(value, list) else [value]
    out: list[str] = []
    for item in raw:
        if isinstance(item, dict):
            out.append(item.get("definition_ref") or item.get("source_of_truth_ref") or json.dumps(item, sort_keys=True))
        elif item not in (None, "", []):
            out.append(str(item))
    return out


def _tbr_card_fields(node: dict, ctx: dict, output_ref: str) -> dict:
    gate = node.get("tbr_gate") or {}
    required = bool(gate.get("required", False))
    translator = gate.get("translator") or {}
    bouncer = gate.get("bouncer") or {}
    recorder = gate.get("recorder") or {}
    definition_refs = (_as_ref_list(translator.get("definition_refs"))
                       or _as_ref_list(translator.get("canonical_definitions")))
    semantic_refs = (_as_ref_list(translator.get("source_of_truth_refs"))
                     or _as_ref_list(ctx.get("_source_refs"))
                     or [GRAPH.get("compiled_from", "process/workflow.aac.json")])
    policy_ref = str(bouncer.get("effective_permission_path") or bouncer.get("policy_engine_ref") or "compiled-runtime-no-external-effectors")
    prompt_ref = str(node.get("prompt_ref") or (f"process/prompts/{node['node_id']}.md" if node.get("runtime_mode") in ("C", "A") else "not_applicable:no_prompt"))
    prompt_version = str(node.get("prompt_version") or "not_applicable:no_prompt_version")
    user_ref = str(ctx.get("_user_ref") or ctx.get("_actor_ref") or "TODO: runtime user/actor ref")
    recipient_ref = str(ctx.get("_recipient_ref") or ctx.get("_actor_ref") or "internal_runtime")
    return {
        "tbr_required": required,
        "prompt_ref": prompt_ref,
        "response_ref": output_ref,
        "tool_call_refs": list(ctx.get("_tool_call_refs") or ["none:runtime_has_no_tool_effectors"]),
        "user_ref": user_ref,
        "recipient_ref": recipient_ref,
        "tbr": {
            "definition_refs": definition_refs,
            "permission_decision": {
                "allowed": True,
                "policy_ref": policy_ref,
                "reason": "runtime has no external effectors; node access is constrained to supplied context, handlers, and card policy refs",
            },
            "semantic_source_refs": semantic_refs,
            "prompt_ref": prompt_ref,
            "prompt_version": prompt_version,
            "response_ref": output_ref,
            "tool_call_refs": list(ctx.get("_tool_call_refs") or ["none:runtime_has_no_tool_effectors"]),
            "user_ref": user_ref,
            "recipient_ref": recipient_ref,
            "retention_class": recorder.get("retention_class") or "TODO: runtime log retention class",
            "tamper_evidence": recorder.get("tamper_evidence") or "TODO: runtime tamper-evidence mechanism",
            "audit_notes": "TBR proof emitted by AAC Factory runtime; live API/resource enforcement must still happen at the source/proxy boundary.",
            "trace_fields": recorder.get("trace_fields") or [
                "run_id", "workflow", "node_id", "runtime_mode", "input_ref", "output_ref",
                "prompt_ref", "prompt_version", "response_ref", "tool_call_refs", "user_ref", "recipient_ref",
                "source_refs", "definition_refs", "permission_decision", "gate_outcomes", "refuse",
                "external_actions_taken", "retention_class", "tamper_evidence",
            ],
        },
    }


def run_graph(trigger_ctx: dict | None = None, *, parent_run_id: str | None = None,
              candidate_ref: str | None = None) -> dict:
    run_id = f"run-{uuid.uuid4().hex[:10]}"
    ctx = dict(trigger_ctx or {})
    ctx.update({"_run_id": run_id, "_workflow": GRAPH["workflow_id"], "_ref": ctx.get("_ref", "manual")})
    report: list[str] = []
    current = GRAPH["entry"]
    visited = 0

    while current not in SINKS and visited < 50:
        node = GRAPH["nodes"][current]
        t0 = now()
        out, gates, adapter = execute_node(node, ctx, report)
        nxt = route(node, out)
        blockers = list(out.get("_certification_blockers") or [])
        output_ref = f"-> {nxt}"
        rc = runcard.new_run_card(
            run_id=f"{run_id}-{visited:02d}", workflow=GRAPH["workflow_id"], node_id=current,
            runtime_mode=node["runtime_mode"], actual_lane=GRAPH["lane"],
            run_kind="batch_child" if parent_run_id else "node",
            parent_run_id=parent_run_id, candidate_ref=candidate_ref,
            ts_start=t0, ts_end=now(),
            input_ref=ctx.get("_ref", "ctx"), output_ref=output_ref,
            gate_outcomes=gates, source_refs=[GRAPH["compiled_from"]],
            confidence=out.get("confidence") if node["runtime_mode"] in ("C", "A") else None,
            model=node.get("model") if node["runtime_mode"] in ("C", "A") else None,
            prompt_version=node.get("prompt_version") if node["runtime_mode"] in ("C", "A") else None,
            certification_blockers=blockers,
            refuse={"refused": nxt in ("refuse_sink", "hard_refuse_sink"),
                    "hard": nxt == "hard_refuse_sink",
                    "reason": (str(out.get("reason") or "")
                               or (f"routed to {nxt} by edge condition" if nxt in ("refuse_sink", "hard_refuse_sink") else ""))},
            escalation={"escalated": bool(out.get("_below_floor")),
                        "reason": "confidence_below_floor" if out.get("_below_floor") else ""},
            **_tbr_card_fields(node, ctx, output_ref),
            **_adapter_card_fields(adapter),
        )
        runcard.write_run_card(PKG, rc)
        ctx.update({k: v for k, v in out.items() if not k.startswith("_")})
        report.append(f"{current} [{node['runtime_mode']}] -> {nxt}")
        current = nxt
        visited += 1

    outcome = current if current in SINKS else "max_steps_reached"
    summary = {"status": "ok", "run_id": run_id, "outcome": outcome,
               "steps": visited, "external_actions_taken": 0, "trace": report}
    out_dir = PKG / "process" / "run-cards" / "_runs"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / f"{run_id}.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    return summary


def run_batch(candidates: list[Any], base_ctx: dict) -> dict:
    batch_id = f"batch-{uuid.uuid4().hex[:10]}"
    child_refs: list[str] = []
    counts = {"include": 0, "skip": 0, "refuse": 0, "hard_refuse": 0, "gate_failure": 0}
    for i, candidate in enumerate(candidates):
        item_ctx = {k: v for k, v in base_ctx.items() if k != "candidates"}
        item_ctx["candidate"] = candidate
        item_ctx["_ref"] = item_ctx.get("_ref") or f"candidate:{i}"
        summary = run_graph(item_ctx, parent_run_id=batch_id, candidate_ref=str(item_ctx["_ref"]))
        child_refs.append(summary["run_id"])
        if summary["outcome"] == "hard_refuse_sink":
            counts["hard_refuse"] += 1
        elif summary["outcome"] == "refuse_sink":
            counts["refuse"] += 1
        else:
            decision = "include" if summary["outcome"] == "happy_sink" else "skip"
            counts[decision] += 1
    parent = {
        "status": "ok", "run_id": batch_id, "run_kind": "batch_parent",
        "workflow": GRAPH["workflow_id"], "candidate_count": len(candidates),
        "child_run_refs": child_refs, "counts": counts,
        "batch_failure_policy": "item_scoped_until_threshold",
        "external_actions_taken": 0,
    }
    out_dir = PKG / "process" / "run-cards" / "_runs"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / f"{batch_id}.json").write_text(json.dumps(parent, indent=2) + "\n", encoding="utf-8")
    rc = runcard.new_run_card(
        run_id=batch_id, workflow=GRAPH["workflow_id"], node_id="batch", runtime_mode="D",
        run_kind="batch_parent", actual_lane=GRAPH["lane"], ts_start=now(), ts_end=now(),
        input_ref=base_ctx.get("_ref", "batch"), output_ref="process/run-cards/_runs/" + batch_id + ".json",
        gate_outcomes={"input": "pass", "output": "pass", "cross_check": "not_run", "action": "pass (no effectors exist)"},
        refuse={"refused": False, "hard": False, "reason": ""}, source_refs=[GRAPH["compiled_from"]],
        external_actions_taken=0,
    )
    runcard.write_run_card(PKG, rc)
    return parent


def run_once(trigger_ctx: dict | None = None) -> dict:
    if kill_switch_active():
        return {"status": "killed", "note": "KILL file present — remove build/KILL to re-enable"}
    ctx = dict(trigger_ctx or {})
    candidates = ctx.get("candidates")
    if isinstance(candidates, list):
        return run_batch(candidates, ctx)
    return run_graph(ctx)


if __name__ == "__main__":
    ctx = json.loads(sys.argv[1]) if len(sys.argv) > 1 else {}
    print(json.dumps(run_once(ctx), indent=2))
