#!/usr/bin/env python3
"""
AAC Factory compiled-agent runtime. Generated by compile_agent.py — edit handlers/, not this.

Walks the compiled graph (nodes.json), enforcing per-node contracts at runtime:
  input gate -> execute (D handler / C llm / H queue) -> output gate (confidence floor,
  hard-refuse scan, leak scan) -> route by edge conditions -> run card per execution.

Safety properties (physical, not policy):
  - There are NO external effectors in this runtime. external_actions_taken is always 0.
    Send/write/pay code is absent below the promoted lane, not disabled.
  - A KILL file at the build root aborts every run (the card's kill_switch maps here).
  - Refusal is first-class: unroutable, low-confidence, gate-failed, and hard-refuse
    outcomes land in refuse/hard-refuse sinks with reasons, and escalations queue for
    the human-over-the-loop review (process/run-cards/_review_queue/).
"""

from __future__ import annotations

import json
import re
import sys
import time
import uuid
from pathlib import Path

BUILD = Path(__file__).resolve().parent
PKG = BUILD.parent.parent  # build/agent -> package root
sys.path.insert(0, str(BUILD))

import llm_adapters  # noqa: E402
import runcard  # noqa: E402  (copied in at compile time)

GRAPH = json.loads((BUILD / "nodes.json").read_text(encoding="utf-8"))
SINKS = {"happy_sink", "refuse_sink", "hard_refuse_sink"}
LEAK_PATTERNS = [re.compile(p) for p in (
    r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-z]{2,}",
    r"\b\(?\d{3}\)?[-.\s]\d{3}[-.\s]\d{4}\b",
    r"\b\d{3}-\d{2}-\d{4}\b",
)]


def now() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def kill_switch_active() -> bool:
    return (BUILD.parent / "KILL").exists()


def hard_refuse_hit(text: str, classes: list[str]) -> str | None:
    for pat in LEAK_PATTERNS:
        if pat.search(text):
            return "leak_pattern_detected"
    low = text.lower()
    for c in classes:
        token = c.split(":")[0].strip().lower()[:40]
        if token.startswith("phi") and "patient" in low:
            return c
    return None


def eval_condition(cond: str, out: dict) -> bool | None:
    """Deterministic router over the small condition grammar the compiler accepts.
    Returns None when a condition is not machine-evaluable (routes to refuse)."""
    c = (cond or "").strip().lower()
    if c in ("always", ""):
        return True
    m = re.match(r"confidence\s*(>=|<)\s*([0-9.]+)", c)
    if m:
        conf = float(out.get("confidence") or 0)
        return conf >= float(m.group(2)) if m.group(1) == ">=" else conf < float(m.group(2))
    m = re.match(r"(\w+)\s*=\s*([\w-]+)", c)
    if m:
        return str(out.get(m.group(1), "")).strip().lower() == m.group(2)
    m = re.match(r"(\w+)\s+in\s+\[([^\]]+)\]", c)
    if m:
        vals = [v.strip().lower() for v in m.group(2).split(",")]
        return str(out.get(m.group(1), "")).strip().lower() in vals
    return None


def execute_node(node: dict, ctx: dict, report: list[str]) -> tuple[dict, dict]:
    """Returns (output, gate_outcomes)."""
    gates = {"input": "pass", "output": "not_run", "cross_check": "not_run", "action": "pass (no effectors exist)"}
    rm = node["runtime_mode"]

    if rm == "H":
        qdir = PKG / "process" / "run-cards" / "_review_queue"
        qdir.mkdir(parents=True, exist_ok=True)
        item = {"node_id": node["node_id"], "ctx_ref": ctx.get("_ref", ""), "queued_at": now(),
                "payload_excerpt": json.dumps(ctx, default=str)[:1500]}
        (qdir / f"{node['node_id']}__{ctx['_run_id']}.json").write_text(
            json.dumps(item, indent=2) + "\n", encoding="utf-8")
        gates["output"] = "pass (queued for human)"
        return {"decision": "queued_for_human", "confidence": 1.0}, gates

    if rm == "D":
        try:
            handler = __import__(f"handlers.{node['module']}", fromlist=["run"])
            out = handler.run(dict(ctx))
            if out.get("_unimplemented"):
                gates["input"] = gates["output"] = "skipped_unimplemented_handler"
                report.append(f"{node['node_id']}: handler unimplemented — pass-through (shadow only)")
                return {**ctx, "_unimplemented": True, "decision": "pass_through", "confidence": 1.0}, gates
            gates["output"] = "pass"
            return out, gates
        except Exception as e:
            gates["output"] = f"fail ({type(e).__name__})"
            return {"decision": "refuse", "confidence": 0.0, "reason": f"handler error: {e}"}, gates

    # C/A: LLM judgment via the node's harness
    sys_prompt = (BUILD / "prompts" / f"{node['module']}.md").read_text(encoding="utf-8")
    user_payload = json.dumps({k: v for k, v in ctx.items() if not k.startswith("_")},
                              default=str)[: node.get("token_budget_chars", 24000)]
    raw = llm_adapters.complete(node["execution"], node.get("model", ""), sys_prompt, user_payload)
    try:
        out = json.loads(raw[raw.find("{"): raw.rfind("}") + 1])
    except Exception:
        gates["output"] = "fail (non-json output)"
        return {"decision": "refuse", "confidence": 0.0, "reason": "model output not parseable"}, gates

    hr = hard_refuse_hit(json.dumps(out, default=str), node.get("hard_refuse", []))
    if hr:
        gates["output"] = f"hard_refuse ({hr})"
        return {"decision": "hard_refuse", "confidence": 1.0, "reason": hr}, gates

    floor = node.get("confidence_floor", 0.6)
    conf = float(out.get("confidence") or 0)
    bounded = node.get("bounded_actions") or []
    if bounded and str(out.get("decision", "")) not in bounded:
        gates["output"] = "fail (decision outside bounded set)"
        return {"decision": "refuse", "confidence": conf, "reason": "unbounded decision"}, gates
    if conf < floor:
        gates["output"] = f"below_floor ({conf} < {floor}) -> human"
        out["_below_floor"] = True
    else:
        gates["output"] = "pass"
    return out, gates


def route(node: dict, out: dict) -> str:
    if out.get("decision") == "hard_refuse":
        return "hard_refuse_sink"
    if out.get("_below_floor"):
        return node.get("below_floor_route", "refuse_sink")
    unmatched_unroutable = False
    for e in node.get("edges", []):
        verdict = eval_condition(e["condition"], out)
        if verdict is True:
            return e["to"]
        if verdict is None:
            unmatched_unroutable = True
    if unmatched_unroutable:
        return "refuse_sink"
    return node.get("default_route", "refuse_sink")


def run_once(trigger_ctx: dict | None = None) -> dict:
    if kill_switch_active():
        return {"status": "killed", "note": "KILL file present — remove build/KILL to re-enable"}
    run_id = f"run-{uuid.uuid4().hex[:10]}"
    ctx = dict(trigger_ctx or {})
    ctx.update({"_run_id": run_id, "_workflow": GRAPH["workflow_id"], "_ref": ctx.get("_ref", "manual")})
    report: list[str] = []
    current = GRAPH["entry"]
    visited = 0
    outcome = "incomplete"

    while current not in SINKS and visited < 50:
        node = GRAPH["nodes"][current]
        t0 = now()
        out, gates = execute_node(node, ctx, report)
        nxt = route(node, out)
        rc = runcard.new_run_card(
            run_id=f"{run_id}-{visited:02d}", workflow=GRAPH["workflow_id"], node_id=current,
            runtime_mode=node["runtime_mode"], actual_lane=GRAPH["lane"],
            ts_start=t0, ts_end=now(),
            input_ref=ctx.get("_ref", "ctx"), output_ref=f"-> {nxt}",
            gate_outcomes=gates, source_refs=[GRAPH["compiled_from"]],
            confidence=out.get("confidence") if node["runtime_mode"] in ("C", "A") else None,
            model=node.get("model") if node["runtime_mode"] in ("C", "A") else None,
            prompt_version=node.get("prompt_version") if node["runtime_mode"] in ("C", "A") else None,
            refuse={"refused": nxt in ("refuse_sink", "hard_refuse_sink"),
                    "hard": nxt == "hard_refuse_sink",
                    "reason": (str(out.get("reason") or "")
                               or (f"routed to {nxt} by edge condition" if nxt in ("refuse_sink", "hard_refuse_sink") else ""))},
            escalation={"escalated": bool(out.get("_below_floor")),
                        "reason": "confidence_below_floor" if out.get("_below_floor") else ""},
        )
        runcard.write_run_card(PKG, rc)
        ctx.update({k: v for k, v in out.items() if not k.startswith("_")})
        report.append(f"{current} [{node['runtime_mode']}] -> {nxt}")
        current = nxt
        visited += 1

    outcome = current if current in SINKS else "max_steps_reached"
    summary = {"status": "ok", "run_id": run_id, "outcome": outcome,
               "steps": visited, "external_actions_taken": 0, "trace": report}
    out_dir = PKG / "process" / "run-cards" / "_runs"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / f"{run_id}.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    return summary


if __name__ == "__main__":
    ctx = json.loads(sys.argv[1]) if len(sys.argv) > 1 else {}
    print(json.dumps(run_once(ctx), indent=2))
